metadata:
  labels:
    expose: "true"
    promotion-group: "ocp-demo-cicd"
  name: "ocp-demo-cicd"
spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
