
metadata:
  labels:
    expose: "true"
    promotion-group: "ocp-demo-cicd"
  name: "ocp-demo-cicd"
spec:
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
  selector:
    project: "ocp-demo-cicd"
